### ISSUE TITLE
Statistics.ts needs rewrite

### ISSUE THREAD

**Issue by IAmBitfrost** [Mr1upMachine/rusty-bot#38]
Redo logic and ensure are variables are correctly null/undefined-checked.

**Comment by Mr1upMachine** [comment]
@IAmBitfrost We should turn on strict mode for TS

**Comment by IAmBitfrost** [comment]
> @IAmBitfrost We should turn on strict mode for TS

I thought we already did? If not then I'm totally in agreement

**Comment by Mr1upMachine** [comment]
Plz fix

**Comment by IAmBitfrost** [comment]
Closed with https://github.com/Mr1upMachine/rusty-bot/pull/89
