### ISSUE TITLE
Status command updates

### ISSUE THREAD

**Issue by IAmBitfrost** [Mr1upMachine/rusty-bot#72]
Similar deal with this one. We might be able to modify this command to take an additional argument if one of these two options is specified, but I'm unsure.

_Originally posted by @IAmBitfrost in https://github.com/Mr1upMachine/rusty-bot/pull/70#discussion_r701476841_

See if slash command builder can decide on variable requirement based on other variable inputs

**Comment by Mr1upMachine** [comment]
No more status command means this is no longer necessary
